{{- if .Values.issuer.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.issuer.privateKeySecretRef }}
  namespace: magento
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.issuer.email }}
    privateKeySecretRef:
      name: {{ .Values.issuer.privateKeySecretRef }}
    solvers:
      - http01:
          ingress:
            class: nginx
{{- end }}
